<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>7.3</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>PromptFavorites</RootNamespace>
    <AssemblyName>PromptFavorites</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../组件库与组件使用示例demo/src/StartUI4Controls/StartUI4Controls.csproj" />
  </ItemGroup>
</Project>
